version: "3.1"

services:
  php:
    build: docker/php
    volumes:
    - ~/.composer-docker/cache:/root/.composer/cache:delegated
    - ./:/app:delegated
    environment:
      PHP_ENABLE_XDEBUG: "${PHP_ENABLE_XDEBUG}"
    ports:
    - '8000:80'
    networks:
    - app_net
    links:
    - db
    depends_on:
    - db
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DB}"
    networks:
    - app_net
    ports:
    - '3307:3306'
    volumes:
    - "${MYSQL_DATA_DIR}:/var/lib/mysql"
    - "${MYSQL_LOG_DIR}:/var/log/mysql"

networks:
  app_net:
    driver: bridge